### PR TITLE
Move config to sdmc:/config/Fizeau

### PR DESCRIPTION
**Pull request by Ammako**
Just need to add the thing to check and prioritise the old location for config, will look into that soon.

#32

### CODE REVIEW

**Comment by Ammako** [comment]
93148ea breaks chainloader functionality for me, I had to revert it locally for testing.

There's probably a better way to do this, but this is what I have.

Overlay is untested because I don't use that stuff, but I see no reason why it wouldn't work (knock on wood.)

**Comment by averne** [comment]
I think I would do something like this:
```cpp
constexpr std::array config_locations = {
    "/switch/Fizeau/config.ini,"
    "/config/Fizeau/config.ini",
};

auto find_config() {
    stat tmp;
    for (auto loc: locations) {
        if (stat(loc, &tmp) == 0)
            return loc;
    }
    return config_locations[0];
};
```
then use `find_config()` instead of the path.

**Comment by Ammako** [comment]
Cool beans.

**Comment by averne** [comment]
Thanks, one last thing: could you move the locations to config.cpp? It's generating a lot of warnings.
Otherwise I just tested your changes and everything seems fine.

**Comment by averne** [comment]
Perfect, thanks again for your PR.

**Pull request merged**
